[package]
name = "spidriver"
version = "0.1.0"
authors = ["Martin Atkins <mart@degeneration.co.uk>"]
edition = "2018"

[dependencies]
embedded-hal = "^0.2.3"
nb = "^0.1.2"

[dev-dependencies]
serial-embedded-hal = "0.1.2"
